In [15]:
%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression, LogisticRegressionCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['target'] = iris.target

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
df['flower_type'] = [iris.target_names[i] for i in df['target']]

In [27]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,flower_type
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

In [28]:
X = df.drop(['target', 'flower_type'], axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [29]:
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)

RandomForestClassifier()

In [30]:
random_forest.score(X_test, y_test)

0.9666666666666667

In [31]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
141                6.9               3.1                5.1               2.3
106                4.9               2.5                4.5               1.7
30                 4.8               3.1                1.6               0.2
12                 4.8               3.0                1.4               0.1
8                  4.4               2.9                1.4               0.2
7                  5.0               3.4                1.5               0.2
11                 4.8               3.4                1.6               0.2
115                6.4               3.2                5.3               2.3
128                6.4               2.8                5.6               2.1
61                 5.9               3.0                4.2               1.5
51                 6.4               3.2                4.5               1.5
142                5.8               2.7                5.1               1.9
58                 6.6               2.9                4.6               1.3
15                 5.7               4.4                1.5               0.4
129                7.2               3.0                5.8               1.6
73                 6.1               2.8                4.7               1.2
6                  4.6               3.4                1.4               0.3
101                5.8               2.7                5.1               1.9
121                5.6               2.8                4.9               2.0
55                 5.7               2.8                4.5               1.3
23                 5.1               3.3                1.7               0.5
125                7.2               3.2                6.0               1.8
67                 5.8               2.7                4.1               1.0
21                 5.1               3.7                1.5               0.4
65                 6.7               3.1                4.4               1.4
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
76                 6.8               2.8                4.8               1.4
123                6.3               2.7                4.9               1.8
75                 6.6               3.0                4.4               1.4

In [32]:
pred = random_forest.predict(X_test)

In [33]:
pred

array([2, 1, 0, 0, 0, 0, 0, 2, 2, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2,
       1, 0, 1, 2, 2, 1, 2, 1])

In [36]:
# If X_test is a DataFrame with your test features
final_df = pd.DataFrame(X_test)
final_df['prediction'] = pred

In [39]:
final_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),prediction
141,6.9,3.1,5.1,2.3,2
106,4.9,2.5,4.5,1.7,1
30,4.8,3.1,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
8,4.4,2.9,1.4,0.2,0
7,5.0,3.4,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
115,6.4,3.2,5.3,2.3,2
128,6.4,2.8,5.6,2.1,2
61,5.9,3.0,4.2,1.5,1
51,6.4,3.2,4.5,1.5,1
142,5.8,2.7,5.1,1.9,2
58,6.6,2.9,4.6,1.3,1
15,5.7,4.4,1.5,0.4,0
129,7.2,3.0,5.8,1.6,2
73,6.1,2.8,4.7,1.2,1
6,4.6,3.4,1.4,0.3,0
101,5.8,2.7,5.1,1.9,2
121,5.6,2.8,4.9,2.0,2
55,5.7,2.8,4.5,1.3,1
23,5.1,3.3,1.7,0.5,0
125,7.2,3.2,6.0,1.8,2
67,5.8,2.7,4.1,1.0,1
21,5.1,3.7,1.5,0.4,0
65,6.7,3.1,4.4,1.4,1
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
76,6.8,2.8,4.8,1.4,1
123,6.3,2.7,4.9,1.8,2
75,6.6,3.0,4.4,1.4,1

In [38]:
final_df.to_csv('predictions.csv', index=False)