Exercise: Build decision tree model to predict survival based on certain parameters

In this file using following columns build a model to predict if person would survive or not,

Pclass

Sex

Age

Fare

Calculate score of your model

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression, LogisticRegressionCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('titanic.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df = df.drop(columns=['Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'])

In [7]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age     Fare
0            1         0       3    male  22.0   7.2500
1            2         1       1  female  38.0  71.2833
2            3         1       3  female  26.0   7.9250
3            4         1       1  female  35.0  53.1000
4            5         0       3    male  35.0   8.0500

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   Fare         891 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.9+ KB

In [8]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
dtype: int64

In [16]:
print(f'average age : {df["Age"].mean()}')
print(f'median age : {df["Age"].median()}')
print(f'most_frequent age : {df["Age"].mode()}')

average age : 29.69911764705882
median age : 28.0
most_frequent age : 0    24.0
Name: Age, dtype: float64

In [20]:
df = df.fillna({"Age": df["Age"].median()})

In [21]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
dtype: int64

In [22]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age     Fare
0            1         0       3    male  22.0   7.2500
1            2         1       1  female  38.0  71.2833
2            3         1       3  female  26.0   7.9250
3            4         1       1  female  35.0  53.1000
4            5         0       3    male  35.0   8.0500

In [23]:
df = pd.get_dummies(df, dtype='int')

In [25]:
passenger_id = df[['PassengerId']]

In [29]:
df = df.drop('PassengerId', axis=1)

In [30]:
df.head()

   Survived  Pclass   Age     Fare  Sex_female  Sex_male
0         0       3  22.0   7.2500           0         1
1         1       1  38.0  71.2833           1         0
2         1       3  26.0   7.9250           1         0
3         1       1  35.0  53.1000           1         0
4         0       3  35.0   8.0500           0         1

In [37]:
features = df.drop('Survived', axis=1) 
target = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

In [38]:
dec_tree = DecisionTreeClassifier()
dec_tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [39]:
dec_tree.score(X_test, y_test)

0.770949720670391

In [40]:
X_test

     Pclass   Age     Fare  Sex_female  Sex_male
141       3  22.0   7.7500           1         0
17        2  28.0  13.0000           0         1
42        3  28.0   7.8958           0         1
655       2  24.0  73.5000           0         1
555       1  62.0  26.5500           0         1
..      ...   ...      ...         ...       ...
513       1  54.0  59.4000           1         0
383       1  35.0  52.0000           1         0
541       3   9.0  31.2750           1         0
563       3  28.0   8.0500           0         1
36        3  28.0   7.2292           0         1

[179 rows x 5 columns]

In [41]:
pred = dec_tree.predict(X_test)

In [42]:
pred

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0])

In [51]:
# Create a DataFrame with the features from X_test
final_df = pd.DataFrame(X_test, columns=['Pclass', 'Age', 'Fare', 'Sex_female', 'Sex_male'])

# Add a new column
final_df['Passenger_Id'] = passenger_id

# Add the predictions as a new column
final_df['predicted'] = pred

In [56]:
#passenger_id

In [57]:
final_df

     Pclass   Age     Fare  Sex_female  Sex_male  Passenger_Id  predicted
141       3  22.0   7.7500           1         0           142          1
17        2  28.0  13.0000           0         1            18          0
42        3  28.0   7.8958           0         1            43          0
655       2  24.0  73.5000           0         1           656          0
555       1  62.0  26.5500           0         1           556          0
..      ...   ...      ...         ...       ...           ...        ...
513       1  54.0  59.4000           1         0           514          1
383       1  35.0  52.0000           1         0           384          1
541       3   9.0  31.2750           1         0           542          0
563       3  28.0   8.0500           0         1           564          0
36        3  28.0   7.2292           0         1            37          0

[179 rows x 7 columns]

In [59]:
final_df = final_df.reset_index()

In [60]:
final_df

,index,Pclass,Age,Fare,Sex_female,Sex_male,Passenger_Id,predicted
0,141,3,22.0,7.7500,1,0,142,1
1,17,2,28.0,13.0000,0,1,18,0
2,42,3,28.0,7.8958,0,1,43,0
3,655,2,24.0,73.5000,0,1,656,0
4,555,1,62.0,26.5500,0,1,556,0
...,...,...,...,...,...,...,...,...
174,513,1,54.0,59.4000,1,0,514,1
175,383,1,35.0,52.0000,1,0,384,1
176,541,3,9.0,31.2750,1,0,542,0
177,563,3,28.0,8.0500,0,1,564,0
178,36,3,28.0,7.2292,0,1,37,0

In [58]:
final_df.to_csv('predicted.csv', index=False)