In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [4]:
pass_id = df['PassengerId']

In [5]:
df = df.drop(columns=['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'])

In [6]:
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [7]:
df.isna().sum()

Pclass        0
Sex           0
Age         177
Fare          0
Survived      0
dtype: int64

In [8]:
mean_age = df['Age'].mean()
median_age = df['Age'].median()
mode_age = df['Age'].mode()

In [9]:
print(mean_age, '\n', median_age, '\n', mode_age)

29.69911764705882
 28.0
 0    24.0
Name: Age, dtype: float64

In [10]:
df = round(df.fillna({'Age': mean_age}), 2)

In [11]:
df.isna().sum()

Pclass      0
Sex         0
Age         0
Fare        0
Survived    0
dtype: int64

In [12]:
df = pd.get_dummies(df, dtype='int')

In [13]:
df.head()

   Pclass   Age   Fare  Survived  Sex_female  Sex_male
0       3  22.0   7.25         0           0         1
1       1  38.0  71.28         1           1         0
2       3  26.0   7.92         1           1         0
3       1  35.0  53.10         1           1         0
4       3  35.0   8.05         0           0         1

In [14]:
df = df.rename(columns={'Sex_female': 'female',	'Sex_male': 'male'})

In [15]:
df.head()

   Pclass   Age   Fare  Survived  female  male
0       3  22.0   7.25         0       0     1
1       1  38.0  71.28         1       1     0
2       3  26.0   7.92         1       1     0
3       1  35.0  53.10         1       1     0
4       3  35.0   8.05         0       0     1

In [16]:
X = df.drop('Survived', axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3)

In [17]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_model.score(X_test, y_test)

0.7985074626865671

In [18]:
pred = nb_model.predict(X_test)
pred

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0])

In [19]:
nb_model.predict_proba(X_test[:10])

array([[0.00260808, 0.99739192],
       [0.92274184, 0.07725816],
       [0.88778534, 0.11221466],
       [0.98934573, 0.01065427],
       [0.98333422, 0.01666578],
       [0.97506276, 0.02493724],
       [0.01409718, 0.98590282],
       [0.91516251, 0.08483749],
       [0.05780909, 0.94219091],
       [0.98896823, 0.01103177]])

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.744     , 0.744     , 0.808     , 0.72580645, 0.84677419])

In [22]:
X_test

     Pclass   Age   Fare  female  male
256       1  29.7  79.20       1     0
120       2  21.0  73.50       0     1
83        1  28.0  47.10       0     1
203       3  45.5   7.22       0     1
489       3   9.0  15.90       0     1
..      ...   ...    ...     ...   ...
622       3  20.0  15.74       0     1
549       2   8.0  36.75       0     1
300       3  29.7   7.75       1     0
186       3  29.7  15.50       1     0
455       3  29.0   7.90       0     1

[268 rows x 5 columns]

In [25]:
pred.shape

(268,)

In [34]:
# Create a DataFrame with the features from X_test
final_df = pd.DataFrame(X_test, columns=['Pclass', 'Age', 'Fare', 'female', 'male'])

In [35]:
# Add the predictions as a new column
final_df['predicted'] = pred

# Add a new column
final_df['Passenger_Id'] = pass_id

In [36]:
final_df

     Pclass   Age   Fare  female  male  predicted  Passenger_Id
256       1  29.7  79.20       1     0          1           257
120       2  21.0  73.50       0     1          0           121
83        1  28.0  47.10       0     1          0            84
203       3  45.5   7.22       0     1          0           204
489       3   9.0  15.90       0     1          0           490
..      ...   ...    ...     ...   ...        ...           ...
622       3  20.0  15.74       0     1          0           623
549       2   8.0  36.75       0     1          0           550
300       3  29.7   7.75       1     0          1           301
186       3  29.7  15.50       1     0          1           187
455       3  29.0   7.90       0     1          0           456

[268 rows x 7 columns]

In [37]:
final_df.to_csv('predicted_results.csv', index=False)